// Generated by gencpp from file lab1_pkg/GetTemp.msg
// DO NOT EDIT!


#ifndef LAB1_PKG_MESSAGE_GETTEMP_H
#define LAB1_PKG_MESSAGE_GETTEMP_H

#include <ros/service_traits.h>


#include <lab1_pkg/GetTempRequest.h>
#include <lab1_pkg/GetTempResponse.h>


namespace lab1_pkg
{

struct GetTemp
{

typedef GetTempRequest Request;
typedef GetTempResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTemp
} // namespace lab1_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab1_pkg::GetTemp > {
  static const char* value()
  {
    return "d01063b0c7298c924d7b67c818285cbb";
  }

  static const char* value(const ::lab1_pkg::GetTemp&) { return value(); }
};

template<>
struct DataType< ::lab1_pkg::GetTemp > {
  static const char* value()
  {
    return "lab1_pkg/GetTemp";
  }

  static const char* value(const ::lab1_pkg::GetTemp&) { return value(); }
};


// service_traits::MD5Sum< ::lab1_pkg::GetTempRequest> should match 
// service_traits::MD5Sum< ::lab1_pkg::GetTemp > 
template<>
struct MD5Sum< ::lab1_pkg::GetTempRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab1_pkg::GetTemp >::value();
  }
  static const char* value(const ::lab1_pkg::GetTempRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab1_pkg::GetTempRequest> should match 
// service_traits::DataType< ::lab1_pkg::GetTemp > 
template<>
struct DataType< ::lab1_pkg::GetTempRequest>
{
  static const char* value()
  {
    return DataType< ::lab1_pkg::GetTemp >::value();
  }
  static const char* value(const ::lab1_pkg::GetTempRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab1_pkg::GetTempResponse> should match 
// service_traits::MD5Sum< ::lab1_pkg::GetTemp > 
template<>
struct MD5Sum< ::lab1_pkg::GetTempResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab1_pkg::GetTemp >::value();
  }
  static const char* value(const ::lab1_pkg::GetTempResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab1_pkg::GetTempResponse> should match 
// service_traits::DataType< ::lab1_pkg::GetTemp > 
template<>
struct DataType< ::lab1_pkg::GetTempResponse>
{
  static const char* value()
  {
    return DataType< ::lab1_pkg::GetTemp >::value();
  }
  static const char* value(const ::lab1_pkg::GetTempResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB1_PKG_MESSAGE_GETTEMP_H
