// Generated by gencpp from file lab1_pkg/GetTempResponse.msg
// DO NOT EDIT!


#ifndef LAB1_PKG_MESSAGE_GETTEMPRESPONSE_H
#define LAB1_PKG_MESSAGE_GETTEMPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab1_pkg
{
template <class ContainerAllocator>
struct GetTempResponse_
{
  typedef GetTempResponse_<ContainerAllocator> Type;

  GetTempResponse_()
    : city()
    , temp()  {
    }
  GetTempResponse_(const ContainerAllocator& _alloc)
    : city(_alloc)
    , temp(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _city_type;
  _city_type city;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _temp_type;
  _temp_type temp;




  typedef boost::shared_ptr< ::lab1_pkg::GetTempResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab1_pkg::GetTempResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTempResponse_

typedef ::lab1_pkg::GetTempResponse_<std::allocator<void> > GetTempResponse;

typedef boost::shared_ptr< ::lab1_pkg::GetTempResponse > GetTempResponsePtr;
typedef boost::shared_ptr< ::lab1_pkg::GetTempResponse const> GetTempResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab1_pkg::GetTempResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab1_pkg::GetTempResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab1_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'lab1_pkg': ['/home/skysar/Documents/spring18/EE5531/lab1/weather_lab1/lab1/catkin_ws/src/lab1_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab1_pkg::GetTempResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab1_pkg::GetTempResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab1_pkg::GetTempResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab1_pkg::GetTempResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab1_pkg::GetTempResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab1_pkg::GetTempResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab1_pkg::GetTempResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "037192b70d5f13e4d794c67fdfbdac4b";
  }

  static const char* value(const ::lab1_pkg::GetTempResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x037192b70d5f13e4ULL;
  static const uint64_t static_value2 = 0xd794c67fdfbdac4bULL;
};

template<class ContainerAllocator>
struct DataType< ::lab1_pkg::GetTempResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab1_pkg/GetTempResponse";
  }

  static const char* value(const ::lab1_pkg::GetTempResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab1_pkg::GetTempResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string city\n\
string temp\n\
\n\
";
  }

  static const char* value(const ::lab1_pkg::GetTempResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab1_pkg::GetTempResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.city);
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTempResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab1_pkg::GetTempResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab1_pkg::GetTempResponse_<ContainerAllocator>& v)
  {
    s << indent << "city: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.city);
    s << indent << "temp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB1_PKG_MESSAGE_GETTEMPRESPONSE_H
